.TH "BerEnumObject" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BerEnumObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBerObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "berObjectTypes \fBgetBerObjectType\fP ()"
.br
.RI "Get type of \fBBerObject\fP\&. "
.ti -1c
.RI "long long int \fBgetLenght\fP ()"
.br
.RI "Get the Lenght of \fBBerObject\fP representation in BER (including tag and lenght) "
.ti -1c
.RI "std::vector< unsigned char > \fBgetBerRepresentation\fP ()"
.br
.RI "Returns the BER representation of \fBBerObject\fP\&. "
.ti -1c
.RI "\fBBerEnumObject\fP (char value)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "berObjectTypes BerEnumObject::getBerObjectType ()\fC [virtual]\fP"

.PP
Get type of \fBBerObject\fP\&. 
.PP
\fBReturns\fP
.RS 4
berObjectTypes 
.RE
.PP

.PP
Reimplemented from \fBBerObject\fP\&.
.SS "std::vector< unsigned char > BerEnumObject::getBerRepresentation ()\fC [virtual]\fP"

.PP
Returns the BER representation of \fBBerObject\fP\&. 
.PP
\fBReturns\fP
.RS 4
std::vector<unsigned char> 
.RE
.PP

.PP
Reimplemented from \fBBerObject\fP\&.
.SS "long long int BerEnumObject::getLenght ()\fC [virtual]\fP"

.PP
Get the Lenght of \fBBerObject\fP representation in BER (including tag and lenght) 
.PP
\fBReturns\fP
.RS 4
long long int 
.RE
.PP

.PP
Reimplemented from \fBBerObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
