.TH "BerObject" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BerObject \- Base class for all BER objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BerObject\&.h>\fP
.PP
Inherited by \fBBerBoolObject\fP, \fBBerEnumObject\fP, \fBBerIntObject\fP, \fBBerSequenceObject\fP, \fBBerSetObject\fP, \fBBerStringObject\fP, and \fBBerUndefinedObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual berObjectTypes \fBgetBerObjectType\fP ()"
.br
.RI "Get type of \fBBerObject\fP\&. "
.ti -1c
.RI "virtual long long int \fBgetLenght\fP ()"
.br
.RI "Get the Lenght of \fBBerObject\fP representation in BER (including tag and lenght) "
.ti -1c
.RI "virtual std::vector< unsigned char > \fBgetBerRepresentation\fP ()"
.br
.RI "Returns the BER representation of \fBBerObject\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base class for all BER objects\&. 
.SH "Member Function Documentation"
.PP 
.SS "berObjectTypes BerObject::getBerObjectType ()\fC [virtual]\fP"

.PP
Get type of \fBBerObject\fP\&. 
.PP
\fBReturns\fP
.RS 4
berObjectTypes 
.RE
.PP

.PP
Reimplemented in \fBBerBoolObject\fP, \fBBerEnumObject\fP, \fBBerIntObject\fP, \fBBerSequenceObject\fP, \fBBerSetObject\fP, \fBBerStringObject\fP, and \fBBerUndefinedObject\fP\&.
.SS "std::vector< unsigned char > BerObject::getBerRepresentation ()\fC [virtual]\fP"

.PP
Returns the BER representation of \fBBerObject\fP\&. 
.PP
\fBReturns\fP
.RS 4
std::vector<unsigned char> 
.RE
.PP

.PP
Reimplemented in \fBBerBoolObject\fP, \fBBerEnumObject\fP, \fBBerIntObject\fP, \fBBerSequenceObject\fP, \fBBerSetObject\fP, \fBBerStringObject\fP, and \fBBerUndefinedObject\fP\&.
.SS "long long int BerObject::getLenght ()\fC [virtual]\fP"

.PP
Get the Lenght of \fBBerObject\fP representation in BER (including tag and lenght) 
.PP
\fBReturns\fP
.RS 4
long long int 
.RE
.PP

.PP
Reimplemented in \fBBerBoolObject\fP, \fBBerEnumObject\fP, \fBBerIntObject\fP, \fBBerSequenceObject\fP, \fBBerSetObject\fP, \fBBerStringObject\fP, and \fBBerUndefinedObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
