.TH "DatabaseObject" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseObject \- Object representing one row from database\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DatabaseObject\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::vector< unsigned char > \fBget_name\fP ()"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBget_uid\fP ()"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBget_email\fP ()"
.br
.ti -1c
.RI "\fBDatabaseObject\fP (std::vector< unsigned char > name, std::vector< unsigned char > uid, std::vector< unsigned char > email)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object representing one row from database\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
