.TH "EqualityMatchFilter" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EqualityMatchFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFilterObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEqualityMatchFilter\fP (std::vector< unsigned char > attributeDescription, std::vector< unsigned char > assertionValue)"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBgetAttributeDescription\fP ()"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBgetAssertionValue\fP ()"
.br
.ti -1c
.RI "filterTypes \fBgetFilterType\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "filterTypes EqualityMatchFilter::getFilterType ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFilterObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
