.TH "FilterObject" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterObject \- base class for all filter objects  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FilterObject\&.h>\fP
.PP
Inherited by \fBAndFilter\fP, \fBEqualityMatchFilter\fP, \fBNotFilter\fP, \fBOrFilter\fP, and \fBSubstringFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual filterTypes \fBgetFilterType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
base class for all filter objects 

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
