.TH "OrFilter" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OrFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFilterObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "filterTypes \fBgetFilterType\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBFilterObject\fP * > \fBfilters\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "filterTypes OrFilter::getFilterType ()\fC [virtual]\fP"

.PP
Reimplemented from \fBFilterObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
