.TH "searchRequest" 3 "ISA LDAP server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
searchRequest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmessageIDLength\fP"
.br
.ti -1c
.RI "unsigned int \fBsizeLimit\fP"
.br
.ti -1c
.RI "\fBsearchedAttributesType\fP \fBattributes\fP"
.br
.ti -1c
.RI "char * \fBmessageID\fP"
.br
.ti -1c
.RI "int \fBsizeLimit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ISA LDAP server from the source code\&.
